/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */


/**
 *
 * @author AE
 */
public class WelcomeScreen2 extends javax.swing.JDialog {

    /**
     * Creates new form WelcomeScreen2
     */
    public WelcomeScreen2() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblInstructions1 = new javax.swing.JLabel();
        lblInstructions2 = new javax.swing.JLabel();
        lblInstructions3 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        radbtnEasy = new javax.swing.JRadioButton();
        radbtnMedium = new javax.swing.JRadioButton();
        radbuttonHard = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 255));
        lblTitle.setText("Hangman");

        lblInstructions1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInstructions1.setText("Press play to guess letters of the unknown word! ");

        lblInstructions2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInstructions2.setText("Win by guessing the whole word and not have the man fully constructed");

        lblInstructions3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInstructions3.setText("Lose by not fully guess the whole word or have the man fully constructed");

        btnPlay.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 0, 0));
        btnPlay.setText("Play!");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        buttonGroup1.add(radbtnEasy);
        radbtnEasy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radbtnEasy.setForeground(new java.awt.Color(0, 255, 0));
        radbtnEasy.setSelected(true);
        radbtnEasy.setText("Easy");
        radbtnEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnEasyActionPerformed(evt);
            }
        });

        buttonGroup1.add(radbtnMedium);
        radbtnMedium.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radbtnMedium.setForeground(new java.awt.Color(255, 153, 51));
        radbtnMedium.setText("Medium");

        buttonGroup1.add(radbuttonHard);
        radbuttonHard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radbuttonHard.setForeground(new java.awt.Color(255, 0, 0));
        radbuttonHard.setText("Hard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblInstructions2)
                                                        .addComponent(lblInstructions3))
                                                .addContainerGap(18, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(lblInstructions1)
                                                                .addGap(77, 77, 77))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(lblTitle)
                                                                .addGap(149, 149, 149))))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radbtnEasy)
                                .addGap(53, 53, 53)
                                .addComponent(radbtnMedium)
                                .addGap(53, 53, 53)
                                .addComponent(radbuttonHard)
                                .addGap(77, 77, 77))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(21, Short.MAX_VALUE)
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblInstructions1)
                                .addGap(18, 18, 18)
                                .addComponent(lblInstructions2)
                                .addGap(12, 12, 12)
                                .addComponent(lblInstructions3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(radbtnEasy)
                                        .addComponent(radbtnMedium)
                                        .addComponent(radbuttonHard))
                                .addGap(18, 18, 18)
                                .addComponent(btnPlay)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        this.dispose(); //exits from welcome screen
        HangmanCulminating2 obj = new HangmanCulminating2();

        obj.setVisible(true);
        obj.timer();
        //Call on play function for the game to choose and display an unknown word
        if(radbuttonHard.isSelected()){ //makes game hard mode if player chooses that
            obj.play(3);
        }else if(radbtnMedium.isSelected()){ //makes game medium mode if player chooses that
            obj.play(2);
        }else{ //makes game easy mode if player chooses that
            obj.play(1);
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void radbtnEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnEasyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radbtnEasyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeScreen2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblInstructions1;
    private javax.swing.JLabel lblInstructions2;
    private javax.swing.JLabel lblInstructions3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radbtnEasy;
    private javax.swing.JRadioButton radbtnMedium;
    private javax.swing.JRadioButton radbuttonHard;
    // End of variables declaration//GEN-END:variables
}
